In [1]:
# Import libraries
import pandas as pd

In [2]:
# Load data
offices = pd.read_csv("data/office_addresses.csv")
addresses = pd.read_excel("data/employee_information.xlsx")

In [4]:
# Define header for emergency contacts
emergency_contacts_cols = [
    "employee_id", "last_name", "first_name",
    "emergency_contact", "emergency_contact_number", "relationship"
]

# Load emergency contacts sheet
emergency_contacts = pd.read_excel(
    "data/employee_information.xlsx",
    sheet_name="emergency_contacts",
    header=None,
    names=emergency_contacts_cols
)

In [6]:
# Load roles
roles = pd.read_json("data/employee_roles.json", orient="index")

In [7]:
# Merge all data sources
employees = (
    addresses
    .merge(offices, how="left", left_on="employee_country", right_on="office_country")
    .merge(roles, how="left", left_on="employee_id", right_index=True)
    .merge(emergency_contacts, how="left", on="employee_id")
)

In [8]:
# Fill missing office information
office_columns = ["office", "office_country", "office_city", "office_street", "office_street_number"]
employees[office_columns] = employees[office_columns].fillna("Remote")

In [9]:
# Select final columns
final_columns = [
    "employee_id", "employee_first_name", "employee_last_name", "employee_country", 
    "employee_city", "employee_street", "employee_street_number", 
    "emergency_contact", "emergency_contact_number", "relationship", 
    "monthly_salary", "team", "title", "office", "office_country", 
    "office_city", "office_street", "office_street_number"
]

In [11]:
employees_final = employees[final_columns].set_index("employee_id")

# View the results
employees_final

,employee_first_name,employee_last_name,employee_country,employee_city,employee_street,employee_street_number,emergency_contact,emergency_contact_number,relationship,monthly_salary,team,title,office,office_country,office_city,office_street,office_street_number
employee_id,,,,,,,,,,,,,,,,,
A2R5H9,Jax,Hunman,BE,Leuven,Grote Markt,9,Opie Hurst,+32-456-5556-84,Brother,$4500,Leadership,CEO,Leuven Office,BE,Leuven,Martelarenlaan,38.0
H8K0L6,Tara,Siff,GB,London,Baker Street,221,Wendy de Matteo,+44-020-5554-333,Sister,$4500,Leadership,CFO,WeWork Office,GB,London,Old Street,207.0
G4R7V0,Gemma,Sagal,US,New-York,Perry Street,66,John Newmark,+1-202-555-194,Husband,$3000,Sales,Business Developer,ESB Office,US,New York City,Fifth Avenue,350.0
M1Z7U9,Tig,Coates,FR,Paris,Rue de l'Université,7,Venus Noone,+1-202-555-0130,Wife,$2000,People Operations,Office Manager,Remote,Remote,Remote,Remote,Remote